import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ToastProvider } from '@/contexts/ToastContext';
import { AuthGuard, SessionProvider } from '@/components/auth';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'GyN Apartment',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <SessionProvider>
                    <ToastProvider>
                        <AuthGuard>
                            {children}
                        </AuthGuard>
                    </ToastProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
